export const trMessages = {
    "001": "Ürünler",
    "002": "Biz Kimiz?",
    "003": "Bağış Kültürü",
    "004": "Biz önerelim",
    "005": "Paketini Kendin Oluştur",
    "006": "beije Ped",
    "007": "beije Günlük Ped",
    "008": "beije Tampon",
    "009": "beije Kap",
    "010": "Isı Bandı",
    "011": "beije Cycle Essentials",
    "013": "beije Cranberry Essentials",
    "014": "Populer Paketler",
    "015": "Ped Paketleri",
    "016": "Tampon Paketleri",
    "017": "Deneme Paketi",
    "018": "Özel Paketler",
    "019": "Tüm Paketler",
    "020": "Paketler",
    "021": "Kendi Paketini Oluştur",
    "022": "beije Kampüs",
    "023": "2 ayda bir gönderim",
    "024": "Öğrenciler için",
    "025": "Neden beije?",
    "026": "beije Kampüs",
    "027": "beije Nasıl Çalışır?",
    "028": "Fiyat Politikası",
    "029": "Sıkça Sorulan Sorular",
    "030": "Tüm Malzemeler",
    "031": "Felsefemiz",
    "032": "Askıda Ped",
    "033": "Bağış",
    "034": "Arayı açmayalım!",
    "035": "beije’deki yeni ürün ve gelişmeleri sana haber verelim & aylık e-gazetemiz döngü’ye abone ol!",
    "036": "Abone olarak, beije KVKK ve Gizlilik Politikası'nı kabul ediyor ve beije'den haber almayı onaylıyorum.",
    "037": "e-posta adresin",
    "038": "Gönder",
    "039": "2025 beije. Tüm hakları saklıdır.",
    "040": "KVKK",
    "041": "KVKK Başvuru Formu",
    "042": "Üyelik Sözleşmesi",
    "043": "Gizlilik Politikası",
    "044": "Çerez Politikası",
    "045": "Test Sonuçları",
    "046": "Facebook",
    "047": "Instagram",
    "048": "Twitter",
    "049": "Linkedin",
    "050": "Spotify",
    "051": "Blog",
    "052": "Sıkça Sorulan Sorular",
    "053": "Quiz",
    "054": "beije Store",
};