export const enMessages = {
    "001": "Products",
    "002": "About Us",
    "003": "Donation Culture",
    "004": "Suggestions",
    "005": "Create Your Own Package",
    "006": "beije Pad",
    "007": "beije Panty Liners",
    "008": "beije Tampon",
    "009": "beije Cup",
    "010": "Heating Patch",
    "011": "beije Cycle Essentials",
    "013": "beije Cranberry Essentials",
    "014": "Popular Packages",
    "015": "Panty Liner Packages",
    "016": "Tampon Packages",
    "017": "Trial Pack",
    "018": "Curated Packages",
    "019": "All Packages",
    "020": "Packages",
    "021": "Create Your Own Package",
    "022": "beije Campus",
    "023": "2 ayda one shipment",
    "024": "For Students",
    "025": "Why beije?",
    "026": "beije Campus",
    "027": "How it works?",
    "028": "Price Policy",
    "029": "FAQs",
    "030": "All Materials",
    "031": "Our Philosophy",
    "032": "Pads on a Hanger",
    "033": "Charity",
    "034": "Let's keep in touch!",
    "035": "Stay updated on the latest news and subscribe to our monthly newsletter (we promise you won’t regret it!).",
    "036": "By subscribing you agree to our Privacy Policy and provide consent to receive e-mails from beije.",
    "037": "your e-mail address",
    "038": "Submit",
    "039": "2025 beije. All rights reserved.",
    "040": "KVKK",
    "041": "KVKK Application Form",
    "042": "Membership Agreement",
    "043": "Privacy Policy",
    "044": "Cookies Policy",
    "045": "Test Results",
    "046": "Facebook",
    "047": "Instagram",
    "048": "Twitter",
    "049": "Linkedin",
    "050": "Spotify",
    "051": "Blog",
    "052": "FAQs",
    "053": "Quiz",
    "054": "beije Store",
    "055": "How it works?",
    "056": "Let us make a beije package just for you, tailed to your needs and preferences.",
    "057": "Menstrual Products",
    "058": "Supportive Products",
    "059": "Your Special Package",
    "060": "Every 2 months",
    "061": "You can create your own package by adding your preferred amount of Pads, Pantyliners, Tampons and other supporting products to meet your personal needs.",
    "062": "Add to Basket",
    "063": "You can use the Heating Patch for both muscle pain and menstrual cramps.",
    "064": "One bottle of Cycle Essentials contains 32 capsules, enough for two cycles.",
    "065": "One bottle of Cranberry Essentials contains 30 capsules made entirely from vegan ingredients.",
    "066": "Most beije users prefer 20 Standard and 20 Super Pads in their subscription package for an average period flow.",
    "067": "68% of our users prefer the Standard Pantyliner on days they have a discharge, and the Super Pantyliner on the last days of their periods or on days with heavier discharge.",
    "068": "Mini Tampon",
    "069": "Standard Tampon",
    "070": "Super Tampon",
    "071": "Your Custom Package",
    "072": "Standard Pad",
    "073": "Super Pad",
    "074": "Super+ Pad",
    "075": "Panty Liner",
    "076": "Super Panty Liner",
    "077": "Thong Panty Liner",
    "078": "beije Cycle Essentials",
    "079": "beije Cranberry Essentials",
    "080": "Heating Patch",
    "081": "2-Pack Heating Patch",
    "082": "4-Pack Heating Patch",

};  