export const trMessages = {
    "001": "Ürünler",
    "002": "Biz Kimiz?",
    "003": "Bağış Kültürü",
    "004": "Biz önerelim",
    "005": "Paketini Kendin Oluştur",
    "006": "beije Ped",
    "007": "beije Günlük Ped",
    "008": "beije Tampon",
    "009": "beije Kap",
    "010": "Isı Bandı",
    "011": "beije Cycle Essentials",
    "013": "beije Cranberry Essentials",
    "014": "Populer Paketler",
    "015": "Ped Paketleri",
    "016": "Tampon Paketleri",
    "017": "Deneme Paketi",
    "018": "Özel Paketler",
    "019": "Tüm Paketler",
    "020": "Paketler",
    "021": "Kendi Paketini Oluştur",
    "022": "beije Kampüs",
    "023": "2 ayda bir gönderim",
    "024": "Öğrenciler için",
    "025": "Neden beije?",
    "026": "beije Kampüs",
    "027": "beije Nasıl Çalışır?",
    "028": "Fiyat Politikası",
    "029": "Sıkça Sorulan Sorular",
    "030": "Tüm Malzemeler",
    "031": "Felsefemiz",
    "032": "Askıda Ped",
    "033": "Bağış",
    "034": "Arayı açmayalım!",
    "035": "beije’deki yeni ürün ve gelişmeleri sana haber verelim & aylık e-gazetemiz döngü’ye abone ol!",
    "036": "Abone olarak, beije KVKK ve Gizlilik Politikası'nı kabul ediyor ve beije'den haber almayı onaylıyorum.",
    "037": "e-posta adresin",
    "038": "Gönder",
    "039": "2025 beije. Tüm hakları saklıdır.",
    "040": "KVKK",
    "041": "KVKK Başvuru Formu",
    "042": "Üyelik Sözleşmesi",
    "043": "Gizlilik Politikası",
    "044": "Çerez Politikası",
    "045": "Test Sonuçları",
    "046": "Facebook",
    "047": "Instagram",
    "048": "Twitter",
    "049": "Linkedin",
    "050": "Spotify",
    "051": "Blog",
    "052": "Sıkça Sorulan Sorular",
    "053": "Quiz",
    "054": "beije Store",
    "055": "Nasıl Çalışır?",
    "056": "Tercih ve ihtiyaçların doğrultusunda seçeceğin ürünlerden ve miktarlardan, sana özel bir paket oluşturalım.",
    "057": "Menstrual Ürünler",
    "058": "Destekleyici Ürünler",
    "059": "Özel Paketin",
    "060": "2 ayda bir gönderim",
    "061": "Kişisel ihtiyacına yönelik istediğin miktarda Ped, Günlük Ped, Tampon veya destekleyici ürünler ekleyerek kendine özel bir paket oluşturabilirsin.",
    "062": "Sepete Ekle",
    "063": "Isı Bandı'nı hem kas ağrıların hem de regl ağrıların için kullanabilirsin!",
    "064": "Cycle Essentials'ın bir şişesi, iki aylık döngüne yetecek miktarda, 32 kapsül içerir.",
    "065": "Cranberry Essentials'ın bir şişesi, tamamı vegan bileşenlerden oluşan 30 kapsül içerir.",
    "066": "Çoğu beije kullanıcısı normal yoğunlukta bir regl dönemi için abonelik paketinde 20 Standart, 20 Süper Ped tercih ediyor.",
    "067": "Kullanıcılarımızın %68'i akıntıları olan günlerde Standart Günlük Ped'i, regllerinin son günlerinde veya daha yoğun akıntıları olan günlerde ise Süper Günlük Ped'i tercih ediyor.",
    "068": "Mini Tampon",
    "069": "Standard Tampon",
    "070": "Super Tampon",
    "071": "Kendi Paketini Oluştur",
    "072": "Standard Pad",
    "073": "Super Pad",
    "074": "Super+ Pad",
    "075": "Günlük Ped",
    "076": "Süper Günlük Ped",
    "077": "Tanga Günlük Ped",
    "078": "beije Cycle Essentials",
    "079": "beije Cranberry Essentials",
    "080": "Isı Bandı",
    "081": "2’li Paket Isı Bandı",
    "082": "4’lü Paket Isı Bandı",
};